apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.app.name }}-service
spec:
  selector:
    app: {{ .Release.Name }}-{{ .Values.app.name }}
  ports:
    - protocol: TCP
      targetPort: {{ .Values.app.name }}-port
      port: {{ .Values.app.port }}
  type: ClusterIP