apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.rabbitmq.name }}
  labels:
    app: {{ .Release.Name }}-{{ .Values.rabbitmq.name }}
spec:
  replicas: {{ .Values.rabbitmq.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.rabbitmq.name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.rabbitmq.name }}
    spec:
      containers:
      - name: {{ .Values.rabbitmq.name }}
        image: {{ .Values.rabbitmq.image }}
        ports:
        - name: {{ .Values.rabbitmq.name }}-port
          containerPort: {{ .Values.rabbitmq.port }}
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: {{ .Values.rabbitmq.user }}
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-app-secret
              key: rmq-pass